<?php

include_once('atrium_opentok.features.inc');

/**
* Implementation of hook_init().
*/
function atrium_opentok_init() {
  drupal_add_css(drupal_get_path('module', 'atrium_opentok') .'/atrium_opentok.css');
}

/**
* Implementation of hook_help().
*/
function atrium_opentok_help($path) {
  // Central help page content.
  if ($path == 'admin/help#atrium_videochat') {
    $help = '<h3>'. t('Video Chat') .'</h3>';
    $help .= '<p>'. t("Video Chat lets you create video chat sessions for you to discuss with your group in realtime") .'</p>';
    $help .= '<p>'. t("To create a session, navigate to the Video Chat section and click the __Add video-chat-og__ button.  Then click __Save__.") .'</p>';
    return $help;
  }

  // Contextual help content.
  if (context_isset('context', 'video_chat')) {
    if ($path == 'node/add/video-chat-og') {
      $help = '';
      $help .= '<h3>'. t('Video Chat') .'</h3>';
      $help .= '<p>'. t("Create a Video Chat Session for your group. Note the date, time, and speaker so everyone knows when to come.") .'</p>';
      return $help;
    }
    else {
      $help = '<h3>'. t('Video Chat') .'</h3>';
      $help .= '<p>'. t("Video Chat lets you video chat sessions for your group. To setup a video chat session, click Add Video Chat.") .'</p>';
      return $help;
    }
  }
}